services:
  - type: web
    name: hashtune-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /
    autoDeploy: true
